-- Create signals table
CREATE TABLE signals (
    id VARCHAR(36) PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('LONG', 'SHORT', 'NEUTRAL')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CLOSED', 'EXPIRED')),
    confidence SMALLINT NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
    expected_return DECIMAL(8, 4) NOT NULL,
    entry_price DECIMAL(12, 4) NOT NULL,
    target_price DECIMAL(12, 4) NOT NULL,
    stop_loss DECIMAL(12, 4) NOT NULL,
    risk_reward_ratio DECIMAL(8, 2) NOT NULL,
    timeframe VARCHAR(10) NOT NULL CHECK (timeframe IN ('1D', '1W', '1M', '3M')),

    -- JDB Methodology Reasoning (stored as JSONB)
    reasoning JSONB NOT NULL,

    -- Timestamps
    generated_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,

    -- Performance tracking (for closed signals)
    actual_return DECIMAL(8, 4),
    exit_price DECIMAL(12, 4),

    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for efficient queries
CREATE INDEX idx_signals_ticker ON signals(ticker);
CREATE INDEX idx_signals_status ON signals(status);
CREATE INDEX idx_signals_type ON signals(type);
CREATE INDEX idx_signals_generated_at ON signals(generated_at DESC);
CREATE INDEX idx_signals_confidence ON signals(confidence DESC);
CREATE INDEX idx_signals_timeframe ON signals(timeframe);
CREATE INDEX idx_signals_reasoning ON signals USING GIN (reasoning);

-- Comments
COMMENT ON TABLE signals IS 'Trading signals generated by JDB methodology';
COMMENT ON COLUMN signals.type IS 'Signal type: LONG (buy), SHORT (sell), NEUTRAL (no action)';
COMMENT ON COLUMN signals.status IS 'Signal status: ACTIVE, CLOSED, EXPIRED';
COMMENT ON COLUMN signals.confidence IS 'Confidence score from 0-100';
COMMENT ON COLUMN signals.reasoning IS 'JSONB containing JDB methodology analysis';
